<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\common.props"/>

    <ItemGroup>
        <PackageReference Include="PPWCode.Vernacular.NHibernate.IV"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\IV\PPWCode.Util.Validation.IV.csproj"/>
    </ItemGroup>

</Project>
