<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\common-tests.props" />

  <PropertyGroup>
    <!-- Target frameworks -->
    <TargetFrameworks>net8.0;net9.0;net10.0;net462;net47;net471;net472;net48;net481</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(OS)' != 'Windows_NT' And $(ContinuousIntegrationBuild) == 'true' ">
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
  </PropertyGroup>

  <!-- Json serialization for .net (core) versions -->
  <ItemGroup Condition="
                     ('$(TargetFramework)' == 'net8.0')
                     Or ('$(TargetFramework)' == 'net9.0')
                     Or ('$(TargetFramework)' == 'net10.0') ">
    <PackageReference Include="Newtonsoft.Json"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\III\PPWCode.Util.Validation.III.csproj"/>
  </ItemGroup>

</Project>
